# This is a basic workflow to help you get started with Actions

name: mule-app-repo-setup-tool

on:
  workflow_dispatch:
    inputs:
      raml-asset-id:
        description: 'Asset ID of RAML Specification in Exchange'
        type: string
      github-pat:
        description: 'GitHub Personal Access Token'
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Checks-out this repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Checks-out the template under $GITHUB_WORKSPACE/template, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: colinlennon/template-demo
          ref: main
          token: ${{ github.event.inputs.github-pat }}
          path: template
        
      # Runs a single command using the runners shell
      - name: Switch to template directory
        run: cd template

      - name: Replace project.artifactId
        run: |
          cd template
          ARTIFACT_ID=${{ github.event.inputs.raml-asset-id }}-impl
          echo "ARTIFACT_ID: $ARTIFACT_ID"          
          ARTIFACT_ID_LINE_NUM=$(grep -n "<!-- PLACEHOLDER: project.artifactId -->" pom.xml | cut -d : -f 1)
          let "ARTIFACT_ID_LINE_NUM=ARTIFACT_ID_LINE_NUM+1"
          sed -i "${ARTIFACT_ID_LINE_NUM}s|<artifactId>.*</artifactId>|<artifactId>${ARTIFACT_ID}</artifactId>|" pom.xml
          sed -i '/<!-- PLACEHOLDER: project.artifactId -->/d' pom.xml
          cat pom.xml    # remove
          
      - name: Replace project.version
        run: |
          cd template
          VERSION_LINE_NUM=$(grep -n "<!-- PLACEHOLDER: project.version -->" pom.xml | cut -d : -f 1)
          let "VERSION_LINE_NUM=VERSION_LINE_NUM+1"
          sed -i "${VERSION_LINE_NUM}s|<version>.*</version>|<version>0.0.1</version>|" pom.xml
          sed -i '/<!-- PLACEHOLDER: project.version -->/d' pom.xml
          cat pom.xml    # remove
          
